kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/dotmesh-io/dotscience-metadata

steps:
- name: test
  image: golang:1.14.0
  commands:
    - make test

- name: slack
  image: plugins/slack
  when:
    status: [ success, failure ]
  settings:
    webhook:
      from_secret: slack_webhook
    channel: ci
    username: drone
    icon_url: https://i.pinimg.com/originals/51/29/a4/5129a48ddad9e8408d2757dd10eb836f.jpg
